"""empty message

Revision ID: b1680677eba5
Revises: 4e3b84755ccb
Create Date: 2017-02-27 02:23:02.165390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1680677eba5'
down_revision = '4e3b84755ccb'
branch_labels = None
depends_on = None


def upgrade():
    from trueskill import Rating

    default_deviation = Rating().sigma

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_deviation', sa.Float(), nullable=False,
                                      default=default_deviation, server_default=str(default_deviation)))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_deviation', sa.Float(), nullable=False,
                                      default=default_deviation, server_default=str(default_deviation)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rating_deviation')

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('rating_deviation')

    # ### end Alembic commands ###
