"""empty message

Revision ID: e4109efc6113
Revises: fef2977e5e2a
Create Date: 2016-12-16 11:40:40.466589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4109efc6113'
down_revision = 'fef2977e5e2a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        lat = sa.sql.table('battles', sa.sql.column('latitude'))
        batch_op.execute(lat.update().values(latitude=1))
        lng = sa.sql.table('battles', sa.sql.column('longitude'))
        batch_op.execute(lng.update().values(longitude=1))
        batch_op.alter_column('latitude', existing_type=sa.FLOAT(),
                              nullable=False)
        batch_op.alter_column('longitude', existing_type=sa.FLOAT(),
                              nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    ### end Alembic commands ###
